package com.defiant.cyanide3d.config;

import org.springframework.context.annotation.Scope;
import org.springframework.stereotype.Component;

import java.io.File;
import java.io.FileInputStream;
import java.io.FileWriter;
import java.io.IOException;
import java.util.Properties;

@Component
@Scope(value = "prototype")
public class Config {

    private final Properties properties;
    private final File configFile;

    private Config() {
        properties = new Properties();
        String config = "config.properties";
        configFile = new File(config);
        if (configFile.isFile()) {
            try {
                properties.load(new FileInputStream(configFile));
            } catch (IOException e) {
                e.printStackTrace();
            }
        } else {
            try {
                properties.store(new FileWriter(configFile), "default autogenerated config");
            } catch (IOException e) {
                e.printStackTrace();
            }
        }
    }


    public String getHost() {
        return properties.getProperty("mail.host");
    }
    public String getUsername() {
        return properties.getProperty("mail.username");
    }
    public String getPassword() {
        return properties.getProperty("mail.password");
    }
    public String getPort() {
        return properties.getProperty("mail.port");
    }
    public String getProtocol() {
        return properties.getProperty("mail.protocol");
    }
}